name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout webui branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: webui

      - name: Build webui branch
        run: |
           npm install
           npm run build

      - name: Copy dist folder to a temporary location
        run: |
          cp -r dist/ ../dist-temp/

      - name: Checkout v1.5.2+ branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: v1.5.2+

      - name: Remove old contents from webroot folder
        run: |
          rm -rf webroot/*

      - name: Copy contents from dist-temp to webroot
        run: |
          cp -r ../dist-temp/* webroot/

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.SUSFS4KSU_SECRET }}
          author_email: "24408329+sidex15@users.noreply.github.com"
          author_name: "sidex15"
          message: 'WebUI: Update webroot with latest build from webui branch (Automated commit)'
          branch: 'v1.5.2+'
          