name: Build and Release

on:
  push:
    paths-ignore:
      - 'README.md'
      - '*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v1.5.2+ branch
        uses: actions/checkout@v4
        with:
          ref: v1.5.2+

      - name: grab zig
        run: |
          curl -L https://ziglang.org/download/0.15.2/zig-x86-linux-0.15.2.tar.xz -o zig.tar.xz
          tar -xf zig.tar.xz
          mv zig-* zig

      - name: grab sstrip from ELFkickers
        run: |
          curl -L https://www.muppetlabs.com/~breadbox/pub/software/ELFkickers-3.2.tar.gz -o sstrip.tar.gz
          tar xf sstrip.tar.gz
          make -C ELFkickers-3.2 sstrip
          cp ELFkickers-3.2/sstrip/sstrip .

      - name: compile binary via zigcc
        run: |
          echo "arch64"
          pwd
          chmod +x sstrip

          zig/zig cc -target aarch64-linux -s -Oz src_mm/magic_mount.c -static -Wl,--gc-sections -o meta-mm 2>&1
          
          wc -c meta-mm
          
          upx --ultra-brute meta-mm
          ./sstrip meta-mm
          
          wc -c meta-mm

          pwd
          
          rm -rf ELFkickers-3.2 zig* sstrip*

      - name: Update version with git HEAD
        run: |
          RANDOM_STRING=$(git rev-parse --short HEAD | cut -c1-7)
          echo "BUILD_ID=${RANDOM_STRING}" >> $GITHUB_ENV
          sed -i "s/version=v1.5.2-R.*/version=v1.5.2-CI-${RANDOM_STRING}/" module.prop

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-1.5.2+_${{ env.BUILD_ID }}
          path: |
            ${{ github.workspace }}/**/*
            !${{ github.workspace }}/.git/**
            !${{ github.workspace }}/.github/**
            !${{ github.workspace }}/node_modules/**
            !${{ github.workspace }}/src/**
            !${{ github.workspace }}/tests/**
